BEGIN;

CREATE TABLE WAREHOUSES
(
    ID        SERIAL PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL
);

CREATE TABLE PRODUCTS
(
    ID     SERIAL PRIMARY KEY,
    NAME   VARCHAR(255)       NOT NULL,
    CODE   VARCHAR(20) UNIQUE NOT NULL,
    SIZE   INT                NOT NULL
);

CREATE TABLE WAREHOUSE_PRODUCTS
(
    ID           SERIAL PRIMARY KEY,
    WAREHOUSE_ID INT REFERENCES WAREHOUSES(ID) ON DELETE CASCADE,
    PRODUCT_ID   INT REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    AMOUNT       INT,
    RESERVED     INT DEFAULT 0,
    UNIQUE (PRODUCT_ID, WAREHOUSE_ID)
);

COMMIT;